# Generated by Django 5.2.4 on 2025-08-04 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_users_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
